version: '3'
services:
  app:
    image: node:21
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - 3000:3000